### ISSUE TITLE
Controller / Gamepad support

### ISSUE THREAD

**Issue by Maingron** [Goel25/tritris#14]
It would be much more relaxing to play the game with a controller. Maybe it is possible to add support for controllers.

**Comment by Goel25** [comment]
I have created a separate function for handling input (https://github.com/Goel25/tritris/blob/main/utility.js#L30). This should make it easier to add controller support. You'll just have to connect the controller, then in that function, if a controller is connected, return a boolean value of whether the button on the controller corresponding to `keyCode` is pressed.

**Comment by Maingron** [comment]
I'm sorry I didn't have time for this yet.
Am currently drowning in a massive backlog with urgent stuff crashing in. I've rescheduled my go-to date to the end of July but it will probably be delayed even further :/

**Comment by Goel25** [comment]
No worries! Multiplayer will be released in a few weeks and, if you've done it by then, I can transfer the gamepad support to there as well.

**Comment by Goel25** [comment]
Thanks to @SuperC03 controller support has been added!
