### ISSUE TITLE
lookahead display

### ISSUE THREAD

**Issue by chrm** [Goel25/tritris#6]
The three single triangles are effectively one tile because they always come
together, but the lookahead display treats them as three seperate tiles. The
problem with this solution is that you don't know what the actual next tile
is when you have to place the first and second part of the triplet. Also you
might get multiple triplets in succession and lose count after the fourth or
fifth single triangle.

My suggestion is to increase the lookahead to three or four tiles and also
treat the triplet as one tile in the lookahead display.

That means if the triplet is the next tile, show three single triangles in
the first lookahead display. While you place the first part of the triplet,
show two single triangles in the first lookahead display. While you place the
second part of the triplet, show one single triangle in the first lookahead
display.

**Comment by Goel25** [comment]
I understand your point, but I actually like that you don't know what the next piece is until the last ninja. It adds another layer of strategy and forces you to place the triangles in such a way that you can accommodate for the next piece, no matter what it ends up being.

When getting two triplets in a row, you also have to be careful to count how many you have.

**Comment by chrm** [comment]
I have a lot more practice now. I was surprised how much easier it gets to
plan ahead without knowing what exactly I will get. One tile lookahead seems
fine to me now. But I still find it very annoying that I don't get to look
ahead when I have to place the most valuable tile.

It's not a problem when I want to fill some holes anyway. It becomes a
problem when I have to decide between filling some holes and clearing three
lines to give me more room.

Why even give the player a lookahead if he doesn't get to use it when placing
the most valuable tile?

**Comment by Goel25** [comment]
I'm glad that you've improved! In my opinion it's part of the strategy to place the 1st ninja in the best location, the next in the 2nd best location, and finally place the 3rd depending on the next piece. It would also be weird for ninjas to keep coming out even though the next piece shows a different piece.

I'm curious to see what other people would say, you can suggest it in the discord.

**Comment by Goel25** [comment]
A suggestion in the Discord was to show how many Ninja pieces are next, similar to what you're saying. The difference is that you still cannot see what the actual next piece is until the last triangle.

Hopefully this update is at least a slight improvement to what you're suggesting.
